-- MySQL Script generated by MySQL Workbench
-- Sat Apr  9 16:37:37 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema webproject
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema webproject
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `webproject` DEFAULT CHARACTER SET utf8 ;
USE `webproject` ;

-- -----------------------------------------------------
-- Table `webproject`.`programmes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webproject`.`programmes` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `desc` VARCHAR(1000) NULL,
  `image` VARCHAR(100) NULL,
  `rating` INT NULL,
  `level` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webproject`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webproject`.`users` (
  `id` INT NOT NULL,
  `username` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `Password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webproject`.`forum`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webproject`.`forum` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `pub` VARCHAR(1000) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_forum_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_forum_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `webproject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webproject`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webproject`.`Admin` (
  `idAdmin` INT NOT NULL,
  `name` VARCHAR(45) NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`idAdmin`),
  INDEX `fk_Admin_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_Admin_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `webproject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `webproject`.`Acheter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `webproject`.`Acheter` (
  `programmes_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`programmes_id`, `users_id`),
  INDEX `fk_programmes_has_users_users1_idx` (`users_id` ASC) VISIBLE,
  INDEX `fk_programmes_has_users_programmes1_idx` (`programmes_id` ASC) VISIBLE,
  CONSTRAINT `fk_programmes_has_users_programmes1`
    FOREIGN KEY (`programmes_id`)
    REFERENCES `webproject`.`programmes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_programmes_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `webproject`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
